# Generated by Django 2.2.1 on 2020-02-04 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('experience', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('form_completion', models.BooleanField(verbose_name='Ease of form completion')),
                ('recommendation', models.CharField(max_length=30)),
            ],
        ),
    ]
